// Sample data for MTPA tourism platform

export const reserves = [
  {
    id: "blyde-river",
    name: "Blyde River Canyon Nature Reserve",
    slug: "blyde-river-canyon",
    location: "Graskop, Mpumalanga",
    region: "Panorama Route",
    coordinates: { lat: -24.5833, lng: 30.8167 },
    description: "One of the largest canyons on Earth and the largest green canyon due to its lush vegetation.",
    shortDescription: "Spectacular green canyon with breathtaking viewpoints",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    gallery: [
      "/blyde-river-canyon-three-rondavels-viewpoint.jpg",
      "/bourkes-luck-potholes-rock-formations.jpg",
      "/gods-window-panorama-view-mpumalanga.jpg",
    ],
    rating: 4.9,
    reviewCount: 1247,
    priceFrom: 450,
    wildlife: ["Hippos", "Crocodiles", "Vervet Monkeys", "Fish Eagles"],
    activities: ["Hiking", "Boat Cruises", "Viewpoints", "Photography"],
    amenities: ["Restaurant", "Curio Shop", "Parking", "Guided Tours"],
    featured: true,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "kruger-gate",
    name: "Kruger Gate Reserve",
    slug: "kruger-gate",
    location: "Hazyview, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -25.0333, lng: 31.1167 },
    description: "Gateway to the world-famous Kruger National Park with exclusive Big Five safari experiences.",
    shortDescription: "Premier Big Five safari destination",
    image: "/african-elephant-kruger-national-park-safari-wildl.jpg",
    gallery: [
      "/lion-pride-resting-african-savanna.jpg",
      "/leopard-in-tree-kruger-park.jpg",
      "/african-buffalo-herd-sunset.jpg",
    ],
    rating: 4.8,
    reviewCount: 2156,
    priceFrom: 1200,
    wildlife: ["Lions", "Elephants", "Leopards", "Rhinos", "Buffalo"],
    activities: ["Game Drives", "Bush Walks", "Bird Watching", "Night Drives"],
    amenities: ["Luxury Lodge", "Swimming Pool", "Spa", "Restaurant"],
    featured: true,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "songimvelo",
    name: "Songimvelo Game Reserve",
    slug: "songimvelo",
    location: "Barberton, Mpumalanga",
    region: "Barberton Valley",
    coordinates: { lat: -25.9667, lng: 31.1000 },
    description: "A hidden gem featuring ancient geology, diverse wildlife, and rich cultural heritage.",
    shortDescription: "Ancient landscapes meet diverse wildlife",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    gallery: [
      "/zebra-herd-african-plains.jpg",
      "/giraffe-silhouette-sunset-africa.jpg",
      "/ancient-rock-formations-barberton.jpg",
    ],
    rating: 4.7,
    reviewCount: 456,
    priceFrom: 380,
    wildlife: ["Zebras", "Giraffes", "Wildebeest", "Antelopes"],
    activities: ["4x4 Trails", "Hiking", "Cultural Tours", "Fishing"],
    amenities: ["Camping", "Chalets", "Braai Areas", "Swimming"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "loskop-dam",
    name: "Loskop Dam Nature Reserve",
    slug: "loskop-dam",
    location: "Middelburg, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -25.4167, lng: 29.3500 },
    description: "A water wonderland perfect for fishing, water sports, and wildlife viewing.",
    shortDescription: "Water sports and wildlife paradise",
    image: "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
    gallery: [
      "/fishing-boat-on-african-dam-sunset.jpg",
      "/white-rhino-grazing-grassland.jpg",
      "/loskop-dam-wildlife.jpg",
    ],
    rating: 4.6,
    reviewCount: 823,
    priceFrom: 320,
    wildlife: ["White Rhinos", "Hippos", "Crocodiles", "Fish Species"],
    activities: ["Fishing", "Boating", "Water Skiing", "Game Viewing"],
    amenities: ["Boat Launch", "Caravan Park", "Chalets", "Shop"],
    featured: true,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "mthethomusha",
    name: "Mthethomusha Game Reserve",
    slug: "mthethomusha",
    location: "Nelspruit, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -25.4500, lng: 30.9833 },
    description: "An exclusive private reserve offering intimate wildlife encounters and luxury accommodation.",
    shortDescription: "Exclusive private game reserve experience",
    image: "/leopard-in-tree-kruger-park.jpg",
    gallery: [
      "/lion-pride-resting-african-savanna.jpg",
      "/african-buffalo-herd-sunset.jpg",
      "/giraffe-silhouette-sunset-africa.jpg",
    ],
    rating: 4.9,
    reviewCount: 312,
    priceFrom: 2500,
    wildlife: ["Wild Dogs", "Cheetahs", "Lions", "Elephants"],
    activities: ["Private Game Drives", "Walking Safaris", "Bush Dining", "Star Gazing"],
    amenities: ["5-Star Lodge", "Private Pool", "Spa", "Fine Dining"],
    featured: true,
    familyFriendly: false,
    accessible: false,
  },
  {
    id: "manyeleti",
    name: "Manyeleti Game Reserve",
    slug: "manyeleti",
    location: "Acornhoek, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -24.7500, lng: 31.4500 },
    description: "One of the oldest private reserves bordering Kruger, offering authentic and uncrowded safari experiences.",
    shortDescription: "Authentic uncrowded Big Five safaris",
    image: "/lion-pride-resting-african-savanna.jpg",
    gallery: [
      "/african-elephant-kruger-national-park-safari-wildl.jpg",
      "/leopard-in-tree-kruger-park.jpg",
      "/african-buffalo-herd-sunset.jpg",
    ],
    rating: 4.8,
    reviewCount: 678,
    priceFrom: 1800,
    wildlife: ["Lions", "Leopards", "Elephants", "Wild Dogs", "Rhinos"],
    activities: ["Game Drives", "Walking Safaris", "Bird Watching", "Photography"],
    amenities: ["Lodge", "Restaurant", "Pool", "WiFi"],
    featured: true,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "barberton-nature",
    name: "Barberton Nature Reserve",
    slug: "barberton-nature",
    location: "Barberton, Mpumalanga",
    region: "Barberton Valley",
    coordinates: { lat: -25.7833, lng: 31.0500 },
    description: "Home to some of the oldest exposed rocks on Earth, this reserve combines geological wonders with diverse wildlife.",
    shortDescription: "Ancient geology meets wildlife conservation",
    image: "/ancient-rock-formations-barberton.jpg",
    gallery: [
      "/barberton-valley.jpg",
      "/zebra-herd-african-plains.jpg",
      "/giraffe-silhouette-sunset-africa.jpg",
    ],
    rating: 4.5,
    reviewCount: 234,
    priceFrom: 280,
    wildlife: ["Mountain Reedbuck", "Oribi", "Bushbuck", "Various Birds"],
    activities: ["Hiking", "Mountain Biking", "Geology Tours", "Bird Watching"],
    amenities: ["Camping", "Picnic Sites", "Trails", "Information Center"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "verloren-valei",
    name: "Verloren Valei Nature Reserve",
    slug: "verloren-valei",
    location: "Dullstroom, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -25.2833, lng: 30.1167 },
    description: "A pristine wetland reserve protecting rare grassland ecosystems and endangered crane species.",
    shortDescription: "Wetland sanctuary for rare birds",
    image: "/highveld-region.jpg",
    gallery: [
      "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
      "/fishing-boat-on-african-dam-sunset.jpg",
    ],
    rating: 4.4,
    reviewCount: 156,
    priceFrom: 150,
    wildlife: ["Wattled Cranes", "Oribi", "Serval", "Various Waterfowl"],
    activities: ["Bird Watching", "Hiking", "Photography", "Fishing"],
    amenities: ["Trails", "Hides", "Parking"],
    featured: false,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "nkomazi",
    name: "Nkomazi Wilderness Reserve",
    slug: "nkomazi-wilderness",
    location: "Komatipoort, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -25.4333, lng: 31.9500 },
    description: "A wild frontier reserve on the Mozambique border, known for exceptional birding and wild landscapes.",
    shortDescription: "Wild frontier birding paradise",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    gallery: [
      "/giraffe-silhouette-sunset-africa.jpg",
      "/zebra-herd-african-plains.jpg",
    ],
    rating: 4.6,
    reviewCount: 189,
    priceFrom: 420,
    wildlife: ["Hippos", "Crocodiles", "African Fish Eagle", "Pel's Fishing Owl"],
    activities: ["Birding", "Canoeing", "Game Drives", "Fishing"],
    amenities: ["Eco-Lodge", "Canoes", "Guided Tours"],
    featured: false,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "malalane-gate",
    name: "Malelane Mountain Reserve",
    slug: "malelane-mountain",
    location: "Malelane, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -25.4833, lng: 31.5167 },
    description: "Scenic mountain reserve at the southern entrance to Kruger, offering diverse landscapes and wildlife.",
    shortDescription: "Southern Kruger gateway with mountain views",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    gallery: [
      "/lion-pride-resting-african-savanna.jpg",
      "/african-elephant-kruger-national-park-safari-wildl.jpg",
    ],
    rating: 4.5,
    reviewCount: 345,
    priceFrom: 550,
    wildlife: ["Elephants", "Lions", "Wild Dogs", "Leopards"],
    activities: ["Game Drives", "Mountain Biking", "Bush Walks"],
    amenities: ["Lodge", "Restaurant", "Pool"],
    featured: false,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "chrissiesmeer",
    name: "Chrissiesmeer Lake District",
    slug: "chrissiesmeer",
    location: "Ermelo, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -26.2833, lng: 30.2167 },
    description: "South Africa's lake district featuring the largest natural lake and exceptional birding opportunities.",
    shortDescription: "SA's lake district and birding hotspot",
    image: "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
    gallery: [
      "/fishing-boat-on-african-dam-sunset.jpg",
      "/highveld-region.jpg",
    ],
    rating: 4.4,
    reviewCount: 198,
    priceFrom: 180,
    wildlife: ["Flamingos", "Pelicans", "Blue Cranes", "Various Waterfowl"],
    activities: ["Birding", "Fishing", "Boating", "Photography"],
    amenities: ["Camping", "Picnic Sites", "Boat Launch"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "witbank-dam",
    name: "Witbank Dam Nature Reserve",
    slug: "witbank-dam",
    location: "eMalahleni, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -25.8667, lng: 29.2333 },
    description: "Urban escape with excellent fishing, water sports, and diverse birdlife near the industrial heartland.",
    shortDescription: "Urban nature escape with water activities",
    image: "/fishing-boat-on-african-dam-sunset.jpg",
    gallery: [
      "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
      "/waterfront-cottage.jpg",
    ],
    rating: 4.2,
    reviewCount: 267,
    priceFrom: 120,
    wildlife: ["Various Fish Species", "Waterbirds", "Small Antelope"],
    activities: ["Fishing", "Sailing", "Picnicking", "Bird Watching"],
    amenities: ["Boat Launch", "Picnic Sites", "Kiosk", "Parking"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "lydenburg",
    name: "Lydenburg Nature Reserve",
    slug: "lydenburg-nature",
    location: "Lydenburg, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -25.1000, lng: 30.4500 },
    description: "Historic reserve in the heart of the escarpment with hiking trails and trout fishing streams.",
    shortDescription: "Escarpment hiking and trout fishing",
    image: "/highveld-region.jpg",
    gallery: [
      "/panorama-route.jpg",
      "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    ],
    rating: 4.3,
    reviewCount: 156,
    priceFrom: 200,
    wildlife: ["Mountain Reedbuck", "Grey Rhebok", "Various Birds"],
    activities: ["Hiking", "Trout Fishing", "Mountain Biking", "Camping"],
    amenities: ["Camping", "Trails", "Fishing Spots"],
    featured: false,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "badplaas",
    name: "Badplaas Forever Resort",
    slug: "badplaas-resort",
    location: "Badplaas, Mpumalanga",
    region: "Barberton Valley",
    coordinates: { lat: -25.9667, lng: 30.5833 },
    description: "Natural hot springs resort with adventure activities, wildlife, and relaxation in the scenic valley.",
    shortDescription: "Hot springs and adventure in nature",
    image: "/barberton-valley.jpg",
    gallery: [
      "/canyon-lodge-pool.jpg",
      "/safari-chalet.jpg",
    ],
    rating: 4.5,
    reviewCount: 512,
    priceFrom: 450,
    wildlife: ["Various Antelope", "Zebras", "Birds"],
    activities: ["Hot Springs", "Zip Lining", "Quad Biking", "Game Drives"],
    amenities: ["Hot Springs", "Spa", "Restaurant", "Adventure Center"],
    featured: true,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "mabusa",
    name: "Mabusa Nature Reserve",
    slug: "mabusa",
    location: "Bushbuckridge, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -24.8333, lng: 31.0500 },
    description: "Community-owned reserve showcasing successful conservation and community partnership models.",
    shortDescription: "Community conservation success story",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    gallery: [
      "/zebra-herd-african-plains.jpg",
      "/giraffe-silhouette-sunset-africa.jpg",
    ],
    rating: 4.4,
    reviewCount: 189,
    priceFrom: 280,
    wildlife: ["Giraffes", "Zebras", "Wildebeest", "Impala", "Warthogs"],
    activities: ["Game Drives", "Community Tours", "Bird Watching", "Cultural Experiences"],
    amenities: ["Community Lodge", "Camping", "Cultural Center"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "mlondozi",
    name: "Mlondozi Dam Nature Reserve",
    slug: "mlondozi-dam",
    location: "Carolina, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -26.0667, lng: 30.1167 },
    description: "Tranquil Highveld reserve surrounding a picturesque dam, ideal for fishing and bird watching.",
    shortDescription: "Peaceful Highveld fishing retreat",
    image: "/fishing-boat-on-african-dam-sunset.jpg",
    gallery: [
      "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
      "/highveld-region.jpg",
    ],
    rating: 4.3,
    reviewCount: 156,
    priceFrom: 180,
    wildlife: ["Various Waterfowl", "Fish Species", "Small Antelope"],
    activities: ["Fishing", "Boating", "Bird Watching", "Picnicking"],
    amenities: ["Boat Launch", "Picnic Sites", "Camping", "Ablutions"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "nooitgedacht",
    name: "Nooitgedacht Dam Nature Reserve",
    slug: "nooitgedacht-dam",
    location: "Ermelo, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -26.4500, lng: 30.1333 },
    description: "Popular Highveld destination combining water sports, fishing, and game viewing opportunities.",
    shortDescription: "Highveld water sports and wildlife",
    image: "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
    gallery: [
      "/fishing-boat-on-african-dam-sunset.jpg",
      "/waterfront-cottage.jpg",
    ],
    rating: 4.4,
    reviewCount: 234,
    priceFrom: 200,
    wildlife: ["Various Antelope", "Zebras", "Waterfowl", "Fish Species"],
    activities: ["Water Skiing", "Fishing", "Game Drives", "Hiking"],
    amenities: ["Chalets", "Camping", "Boat Launch", "Restaurant"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "ohrigstad",
    name: "Ohrigstad Dam Nature Reserve",
    slug: "ohrigstad-dam",
    location: "Ohrigstad, Mpumalanga",
    region: "Panorama Route",
    coordinates: { lat: -24.7000, lng: 30.5333 },
    description: "Scenic reserve in the escarpment offering excellent bass fishing and diverse birdlife.",
    shortDescription: "Escarpment fishing and birding paradise",
    image: "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
    gallery: [
      "/panorama-route.jpg",
      "/fishing-boat-on-african-dam-sunset.jpg",
    ],
    rating: 4.5,
    reviewCount: 178,
    priceFrom: 220,
    wildlife: ["Bass", "Yellowfish", "Various Waterbirds", "Vervet Monkeys"],
    activities: ["Fishing", "Bird Watching", "Hiking", "Mountain Biking"],
    amenities: ["Chalets", "Camping", "Boat Launch", "Hiking Trails"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "mkhombo",
    name: "Mkhombo Nature Reserve",
    slug: "mkhombo",
    location: "Middelburg, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -25.6500, lng: 29.5000 },
    description: "Large Highveld reserve with diverse habitats, excellent game viewing, and scenic dam.",
    shortDescription: "Diverse Highveld wilderness experience",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    gallery: [
      "/white-rhino-grazing-grassland.jpg",
      "/giraffe-silhouette-sunset-africa.jpg",
    ],
    rating: 4.5,
    reviewCount: 289,
    priceFrom: 350,
    wildlife: ["White Rhinos", "Hippos", "Giraffes", "Zebras", "Wildebeest"],
    activities: ["Game Drives", "Fishing", "Bird Watching", "Hiking"],
    amenities: ["Lodge", "Camping", "Restaurant", "Conference Facilities"],
    featured: true,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "sterkspruit",
    name: "Sterkspruit Nature Reserve",
    slug: "sterkspruit",
    location: "Lydenburg, Mpumalanga",
    region: "Panorama Route",
    coordinates: { lat: -25.0500, lng: 30.4000 },
    description: "Mountain reserve protecting high-altitude grasslands and pristine trout streams.",
    shortDescription: "Highland trout fishing sanctuary",
    image: "/highveld-region.jpg",
    gallery: [
      "/panorama-route.jpg",
      "/fishing-boat-on-african-dam-sunset.jpg",
    ],
    rating: 4.6,
    reviewCount: 145,
    priceFrom: 280,
    wildlife: ["Mountain Reedbuck", "Grey Rhebok", "Oribi", "Various Birds"],
    activities: ["Fly Fishing", "Hiking", "Bird Watching", "Photography"],
    amenities: ["Fishing Huts", "Trails", "Parking"],
    featured: false,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "mahushe-shongwe",
    name: "Mahushe Shongwe Game Reserve",
    slug: "mahushe-shongwe",
    location: "Schoemansdal, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -25.6833, lng: 31.2000 },
    description: "Community-owned Big Five reserve offering authentic safari experiences near Kruger.",
    shortDescription: "Community Big Five conservation",
    image: "/lion-pride-resting-african-savanna.jpg",
    gallery: [
      "/african-elephant-kruger-national-park-safari-wildl.jpg",
      "/leopard-in-tree-kruger-park.jpg",
    ],
    rating: 4.6,
    reviewCount: 234,
    priceFrom: 950,
    wildlife: ["Lions", "Elephants", "Leopards", "Buffalo", "Rhinos"],
    activities: ["Game Drives", "Walking Safaris", "Community Tours", "Bird Watching"],
    amenities: ["Safari Lodge", "Restaurant", "Pool", "Community Center"],
    featured: true,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "thornybush",
    name: "Thornybush Nature Reserve",
    slug: "thornybush",
    location: "Hoedspruit, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -24.4167, lng: 31.1667 },
    description: "Premier Big Five reserve with open borders to Kruger, known for exceptional leopard sightings.",
    shortDescription: "Premier leopard viewing destination",
    image: "/leopard-in-tree-kruger-park.jpg",
    gallery: [
      "/lion-pride-resting-african-savanna.jpg",
      "/african-elephant-kruger-national-park-safari-wildl.jpg",
      "/safari-jeep.jpg",
    ],
    rating: 4.9,
    reviewCount: 567,
    priceFrom: 3500,
    wildlife: ["Leopards", "Lions", "Elephants", "Wild Dogs", "Rhinos"],
    activities: ["Game Drives", "Walking Safaris", "Photography Hides", "Bush Dining"],
    amenities: ["Luxury Lodges", "Spa", "Fine Dining", "Private Pools"],
    featured: true,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "sabi-sands",
    name: "Sabi Sands Game Reserve",
    slug: "sabi-sands",
    location: "Sabi Sands, Mpumalanga",
    region: "Lowveld",
    coordinates: { lat: -24.9500, lng: 31.4500 },
    description: "World-renowned private reserve offering unparalleled Big Five encounters and luxury safari lodges.",
    shortDescription: "World-class luxury safari destination",
    image: "/african-elephant-kruger-national-park-safari-wildl.jpg",
    gallery: [
      "/lion-pride-resting-african-savanna.jpg",
      "/leopard-in-tree-kruger-park.jpg",
      "/safari-chalet.jpg",
    ],
    rating: 4.9,
    reviewCount: 1234,
    priceFrom: 5000,
    wildlife: ["Big Five", "Wild Dogs", "Cheetahs", "Hyenas", "Over 350 Bird Species"],
    activities: ["Premium Game Drives", "Walking Safaris", "Photography", "Star Gazing"],
    amenities: ["World-Class Lodges", "Spa", "Fine Dining", "Private Suites"],
    featured: true,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "andover",
    name: "Andover Nature Reserve",
    slug: "andover",
    location: "Pilgrim's Rest, Mpumalanga",
    region: "Panorama Route",
    coordinates: { lat: -24.9167, lng: 30.7833 },
    description: "Historic gold mining area turned nature reserve with indigenous forests and mountain streams.",
    shortDescription: "Gold rush history meets nature",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    gallery: [
      "/panorama-route.jpg",
      "/ancient-rock-formations-barberton.jpg",
    ],
    rating: 4.4,
    reviewCount: 167,
    priceFrom: 180,
    wildlife: ["Bushbuck", "Duiker", "Samango Monkeys", "Various Birds"],
    activities: ["Hiking", "Historical Tours", "Bird Watching", "Gold Panning"],
    amenities: ["Trails", "Picnic Sites", "Historical Museum", "Parking"],
    featured: false,
    familyFriendly: true,
    accessible: true,
  },
  {
    id: "sekhukhune",
    name: "Sekhukhune Nature Reserve",
    slug: "sekhukhune",
    location: "Burgersfort, Mpumalanga",
    region: "Highveld",
    coordinates: { lat: -24.5500, lng: 30.2833 },
    description: "Northern escarpment reserve with unique bushveld vegetation and rich cultural heritage.",
    shortDescription: "Northern escarpment wilderness",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    gallery: [
      "/zebra-herd-african-plains.jpg",
      "/ancient-rock-formations-barberton.jpg",
    ],
    rating: 4.3,
    reviewCount: 98,
    priceFrom: 250,
    wildlife: ["Various Antelope", "Zebras", "Birds of Prey"],
    activities: ["Game Drives", "Cultural Tours", "Hiking", "Rock Art Sites"],
    amenities: ["Basic Accommodation", "Camping", "Cultural Village"],
    featured: false,
    familyFriendly: true,
    accessible: false,
  },
  {
    id: "kranshoek",
    name: "Kranshoek Nature Reserve",
    slug: "kranshoek",
    location: "Sabie, Mpumalanga",
    region: "Panorama Route",
    coordinates: { lat: -25.0833, lng: 30.8167 },
    description: "Indigenous forest reserve protecting rare plant species and offering scenic hiking trails.",
    shortDescription: "Indigenous forest sanctuary",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    gallery: [
      "/panorama-route.jpg",
      "/gods-window-panorama-view-mpumalanga.jpg",
    ],
    rating: 4.5,
    reviewCount: 123,
    priceFrom: 50,
    wildlife: ["Samango Monkeys", "Bushbuck", "Blue Duiker", "Forest Birds"],
    activities: ["Hiking", "Forest Walks", "Bird Watching", "Photography"],
    amenities: ["Trails", "Parking", "Picnic Sites"],
    featured: false,
    familyFriendly: true,
    accessible: false,
  },
]

export const accommodations = [
  {
    id: "canyon-lodge",
    name: "Canyon Lodge & Spa",
    slug: "canyon-lodge-spa",
    reserveId: "blyde-river",
    reserveName: "Blyde River Canyon Nature Reserve",
    type: "Lodge",
    description:
      "Perched on the edge of the canyon with panoramic views and world-class amenities. This luxury lodge offers an unforgettable escape into nature with all modern comforts.",
    image: "/canyon-lodge.jpg",
    gallery: ["/canyon-lodge-pool.jpg", "/canyon-lodge-room.jpg", "/canyon-lodge-deck.jpg"],
    pricePerNight: 2800,
    capacity: 2,
    maxCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: [
      "King Bed",
      "Private Pool",
      "Spa Bath",
      "Fireplace",
      "Mini Bar",
      "WiFi",
      "Air Conditioning",
      "Room Service",
    ],
    rating: 4.9,
    reviewCount: 234,
    featured: true,
  },
  {
    id: "bush-camp",
    name: "Riverside Bush Camp",
    slug: "riverside-bush-camp",
    reserveId: "blyde-river",
    reserveName: "Blyde River Canyon Nature Reserve",
    type: "Camp",
    description:
      "Authentic safari camping experience along the river with modern comforts. Fall asleep to the sounds of the African bush.",
    image: "/bush-camp.jpg",
    gallery: ["/bush-camp-tent.jpg", "/bush-camp-fire.jpg"],
    pricePerNight: 950,
    capacity: 2,
    maxCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Queen Bed", "En-suite", "Deck", "Braai", "Outdoor Shower"],
    rating: 4.7,
    reviewCount: 156,
    featured: false,
  },
  {
    id: "family-chalet",
    name: "Family Safari Chalet",
    slug: "family-safari-chalet",
    reserveId: "kruger-gate",
    reserveName: "Kruger Gate Reserve",
    type: "Chalet",
    description:
      "Spacious family accommodation with private viewing deck and garden. Perfect for families wanting a safari experience.",
    image: "/safari-chalet.jpg",
    gallery: ["/safari-chalet-interior.jpg", "/safari-chalet-deck.jpg"],
    pricePerNight: 1800,
    capacity: 4,
    maxCapacity: 6,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Multiple Beds", "Kitchen", "Lounge", "Private Garden", "BBQ", "Parking", "WiFi"],
    rating: 4.8,
    reviewCount: 412,
    featured: true,
  },
  {
    id: "honeymoon-suite",
    name: "Honeymoon Treehouse Suite",
    slug: "honeymoon-treehouse-suite",
    reserveId: "kruger-gate",
    reserveName: "Kruger Gate Reserve",
    type: "Suite",
    description:
      "Elevated romance in the treetops with stunning views and complete privacy. The ultimate romantic getaway.",
    image: "/treehouse-suite.jpg",
    gallery: ["/treehouse-bedroom.jpg", "/treehouse-bath.jpg"],
    pricePerNight: 4500,
    capacity: 2,
    maxCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["King Bed", "Private Plunge Pool", "Champagne Bar", "Star Bath", "Butler Service"],
    rating: 5.0,
    reviewCount: 89,
    featured: true,
  },
  {
    id: "safari-tent",
    name: "Luxury Safari Tent",
    slug: "luxury-safari-tent",
    reserveId: "songimvelo",
    reserveName: "Songimvelo Game Reserve",
    type: "Tent",
    description:
      "Experience glamping at its finest with canvas walls and five-star amenities in the heart of the bush.",
    image: "/glamping-tent.jpg",
    gallery: ["/glamping-interior.jpg"],
    pricePerNight: 1200,
    capacity: 2,
    maxCapacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Queen Bed", "En-suite", "Deck", "Solar Power", "Eco-Friendly"],
    rating: 4.6,
    reviewCount: 178,
    featured: false,
  },
  {
    id: "dam-cottage",
    name: "Waterfront Cottage",
    slug: "waterfront-cottage",
    reserveId: "loskop-dam",
    reserveName: "Loskop Dam Nature Reserve",
    type: "Cottage",
    description: "Cozy cottage right on the water's edge, perfect for fishing enthusiasts and nature lovers.",
    image: "/waterfront-cottage.jpg",
    gallery: ["/cottage-dock.jpg"],
    pricePerNight: 850,
    capacity: 4,
    maxCapacity: 6,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Fully Equipped Kitchen", "Braai Area", "Boat Jetty Access", "Fishing Gear Storage"],
    rating: 4.5,
    reviewCount: 203,
    featured: false,
  },
  {
    id: "mountain-retreat",
    name: "Dullstroom Mountain Retreat",
    slug: "dullstroom-mountain-retreat",
    reserveId: "verloren-valei",
    reserveName: "Verloren Valei Nature Reserve",
    type: "Lodge",
    description: "Cozy highland lodge with fireplaces and mountain views, perfect for trout fishing enthusiasts.",
    image: "/highveld-region.jpg",
    gallery: ["/canyon-lodge-room.jpg", "/bush-camp-fire.jpg"],
    pricePerNight: 1650,
    capacity: 2,
    maxCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Fireplace", "Mountain Views", "Fishing Access", "Heated Pool", "Restaurant", "WiFi"],
    rating: 4.7,
    reviewCount: 287,
    featured: true,
    coordinates: { lat: -25.2900, lng: 30.1200 },
  },
  {
    id: "bush-villa",
    name: "Manyeleti Bush Villa",
    slug: "manyeleti-bush-villa",
    reserveId: "manyeleti",
    reserveName: "Manyeleti Game Reserve",
    type: "Villa",
    description: "Exclusive bush villa with private pool and dedicated safari vehicle for unforgettable wildlife encounters.",
    image: "/safari-chalet.jpg",
    gallery: ["/safari-chalet-interior.jpg", "/safari-chalet-deck.jpg", "/treehouse-bath.jpg"],
    pricePerNight: 5500,
    capacity: 4,
    maxCapacity: 8,
    bedrooms: 4,
    bathrooms: 4,
    amenities: ["Private Pool", "Safari Vehicle", "Chef", "Butler", "Spa", "Wine Cellar"],
    rating: 4.9,
    reviewCount: 134,
    featured: true,
    coordinates: { lat: -24.7600, lng: 31.4600 },
  },
  {
    id: "riverside-cabin",
    name: "Riverside Fishing Cabin",
    slug: "riverside-fishing-cabin",
    reserveId: "nkomazi",
    reserveName: "Nkomazi Wilderness Reserve",
    type: "Cabin",
    description: "Rustic cabin on the river bank, ideal for tiger fishing and birding enthusiasts.",
    image: "/waterfront-cottage.jpg",
    gallery: ["/cottage-dock.jpg", "/fishing-boat-on-african-dam-sunset.jpg"],
    pricePerNight: 750,
    capacity: 2,
    maxCapacity: 4,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["River Access", "Fishing Gear", "Canoe", "Braai", "Solar Power"],
    rating: 4.4,
    reviewCount: 98,
    featured: false,
    coordinates: { lat: -25.4400, lng: 31.9600 },
  },
  {
    id: "eco-pod",
    name: "Eco Pod Retreat",
    slug: "eco-pod-retreat",
    reserveId: "barberton-nature",
    reserveName: "Barberton Nature Reserve",
    type: "Pod",
    description: "Sustainable eco-pods with panoramic mountain views and minimal environmental footprint.",
    image: "/glamping-tent.jpg",
    gallery: ["/glamping-interior.jpg", "/barberton-valley.jpg"],
    pricePerNight: 980,
    capacity: 2,
    maxCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Panoramic Windows", "Solar Powered", "Outdoor Shower", "Stargazing Deck", "Eco-Friendly"],
    rating: 4.6,
    reviewCount: 167,
    featured: false,
    coordinates: { lat: -25.7900, lng: 31.0600 },
  },
  {
    id: "ermelo-lodge",
    name: "Ermelo Country Lodge",
    slug: "ermelo-country-lodge",
    reserveId: "chrissiesmeer",
    reserveName: "Chrissiesmeer Lake District",
    type: "Lodge",
    description: "Comfortable Highveld lodge with lake views and access to birding hotspots.",
    image: "/canyon-lodge.jpg",
    gallery: ["/canyon-lodge-room.jpg", "/fishing-boat-on-african-dam-sunset.jpg"],
    pricePerNight: 950,
    capacity: 2,
    maxCapacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Lake Views", "Fireplace", "Restaurant", "Fishing Guides", "Bird Hides"],
    rating: 4.3,
    reviewCount: 98,
    featured: false,
    coordinates: { lat: -26.2900, lng: 30.2200 },
  },
  {
    id: "badplaas-chalets",
    name: "Badplaas Hot Spring Chalets",
    slug: "badplaas-hot-spring-chalets",
    reserveId: "badplaas",
    reserveName: "Badplaas Forever Resort",
    type: "Chalet",
    description: "Chalets with private hot spring access and stunning valley views.",
    image: "/safari-chalet.jpg",
    gallery: ["/safari-chalet-interior.jpg", "/barberton-valley.jpg"],
    pricePerNight: 1450,
    capacity: 2,
    maxCapacity: 6,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Private Hot Tub", "Valley Views", "Braai", "Kitchen", "Spa Access"],
    rating: 4.6,
    reviewCount: 234,
    featured: true,
    coordinates: { lat: -25.9700, lng: 30.5900 },
  },
  {
    id: "malelane-lodge",
    name: "Malelane Safari Lodge",
    slug: "malelane-safari-lodge",
    reserveId: "malalane-gate",
    reserveName: "Malelane Mountain Reserve",
    type: "Lodge",
    description: "Exclusive lodge at Kruger's southern gate with Big Five game drives.",
    image: "/safari-chalet.jpg",
    gallery: ["/safari-chalet-deck.jpg", "/lion-pride-resting-african-savanna.jpg"],
    pricePerNight: 3200,
    capacity: 2,
    maxCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Game Drives", "Pool", "Spa", "Fine Dining", "Kruger Access"],
    rating: 4.8,
    reviewCount: 187,
    featured: true,
    coordinates: { lat: -25.4900, lng: 31.5200 },
  },
  {
    id: "lydenburg-farm",
    name: "Lydenburg Trout Farm Stay",
    slug: "lydenburg-trout-farm",
    reserveId: "lydenburg",
    reserveName: "Lydenburg Nature Reserve",
    type: "Farmhouse",
    description: "Working trout farm with cozy accommodation and mountain escarpment views.",
    image: "/waterfront-cottage.jpg",
    gallery: ["/cottage-dock.jpg", "/highveld-region.jpg"],
    pricePerNight: 850,
    capacity: 2,
    maxCapacity: 6,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Trout Fishing", "Farm Experience", "Mountain Views", "Braai", "Hiking"],
    rating: 4.5,
    reviewCount: 112,
    featured: false,
    coordinates: { lat: -25.1100, lng: 30.4600 },
  },
]

export const experiences = [
  {
    id: "sunrise-safari",
    name: "Sunrise Game Drive",
    slug: "sunrise-game-drive",
    category: "Safari",
    duration: "4 hours",
    intensity: "Easy",
    coordinates: { lat: -25.0333, lng: 31.1167 },
    description:
      "Experience the magic of the African bush as it awakens with expert guides. Watch the sunrise over the savanna and spot wildlife at their most active.",
    longDescription:
      "Join our experienced rangers for an unforgettable sunrise game drive through the reserve. As the first light breaks over the African landscape, witness the bush come alive with activity. This is prime time for predator sightings as lions, leopards, and cheetahs are most active during the cooler morning hours.",
    image: "/sunrise-safari.jpg",
    gallery: [
      "/safari-jeep.jpg",
      "/safari-wildlife.jpg",
      "/lion-pride-resting-african-savanna.jpg",
      "/leopard-in-tree-kruger-park.jpg",
    ],
    price: 850,
    rating: 4.9,
    reviewCount: 567,
    includes: ["Expert Guide", "Refreshments", "Binoculars", "Blankets"],
    excludes: ["Meals", "Transport to reserve"],
    featured: true,
    maxParticipants: 8,
    minAge: 6,
  },
  {
    id: "canyon-hike",
    name: "Canyon Rim Trail Hike",
    slug: "canyon-rim-trail-hike",
    category: "Adventure",
    duration: "6 hours",
    intensity: "Moderate",
    coordinates: { lat: -24.5833, lng: 30.8167 },
    description: "Trek along the rim of the magnificent Blyde River Canyon with stunning viewpoints.",
    longDescription:
      "This guided hike takes you along the dramatic rim of Blyde River Canyon, one of the largest green canyons in the world. Stop at iconic viewpoints including God's Window, the Three Rondavels, and Bourke's Luck Potholes.",
    image: "/blyde-river-canyon-three-rondavels-viewpoint.jpg",
    gallery: [
      "/gods-window-panorama-view-mpumalanga.jpg",
      "/bourkes-luck-potholes-rock-formations.jpg",
      "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
      "/panorama-route.jpg",
    ],
    price: 450,
    rating: 4.8,
    reviewCount: 234,
    includes: ["Guide", "Lunch Pack", "Transport", "Water"],
    excludes: ["Hiking boots", "Personal items"],
    featured: true,
    maxParticipants: 12,
    minAge: 10,
  },
  {
    id: "cultural-tour",
    name: "Shangaan Cultural Experience",
    slug: "shangaan-cultural-experience",
    category: "Culture",
    duration: "3 hours",
    intensity: "Easy",
    coordinates: { lat: -25.0500, lng: 31.0833 },
    description: "Immerse yourself in the rich traditions of the Shangaan people.",
    longDescription:
      "Visit an authentic Shangaan village and learn about the customs, traditions, and daily life of one of South Africa's most fascinating cultures. Enjoy traditional dancing, storytelling, and a home-cooked meal.",
    image: "/cultural-village.jpg",
    gallery: [
      "/traditional-dance.jpg",
      "/ancient-rock-formations-barberton.jpg",
      "/barberton-valley.jpg",
      "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    ],
    price: 380,
    rating: 4.7,
    reviewCount: 189,
    includes: ["Village Visit", "Traditional Meal", "Dance Performance", "Cultural Guide"],
    excludes: ["Transport", "Gratuities"],
    featured: false,
    maxParticipants: 20,
    minAge: 0,
  },
  {
    id: "river-cruise",
    name: "Blyde Dam Boat Cruise",
    slug: "blyde-dam-boat-cruise",
    category: "Water",
    duration: "2 hours",
    intensity: "Easy",
    coordinates: { lat: -24.5500, lng: 30.8000 },
    description: "Cruise through the dramatic canyon with opportunities to spot wildlife.",
    longDescription:
      "Glide across the tranquil waters of Blyde Dam, surrounded by towering canyon walls. Keep an eye out for hippos, crocodiles, and a variety of bird species. Our knowledgeable captain will share fascinating facts about the geology and ecology of this unique environment.",
    image: "/dam-boat-cruise.jpg",
    gallery: [
      "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
      "/fishing-boat-on-african-dam-sunset.jpg",
      "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
      "/blyde-river-canyon-three-rondavels-viewpoint.jpg",
    ],
    price: 320,
    rating: 4.6,
    reviewCount: 445,
    includes: ["Boat Trip", "Guide", "Refreshments", "Life Jackets"],
    excludes: ["Meals", "Transport to dam"],
    featured: true,
    maxParticipants: 30,
    minAge: 3,
  },
  {
    id: "hot-air-balloon",
    name: "Hot Air Balloon Safari",
    slug: "hot-air-balloon-safari",
    category: "Adventure",
    duration: "4 hours",
    intensity: "Easy",
    coordinates: { lat: -24.9833, lng: 31.1500 },
    description: "Soar above the African bush at sunrise for an unforgettable aerial safari.",
    longDescription:
      "Drift silently over the African wilderness in a hot air balloon as the sun rises. Watch wildlife below and enjoy breathtaking panoramic views. Land in the bush for a champagne breakfast celebration.",
    image: "/balloon-safari.jpg",
    gallery: [
      "/balloon-landing.jpg",
      "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
      "/giraffe-silhouette-sunset-africa.jpg",
      "/sunrise-safari.jpg",
    ],
    price: 4500,
    rating: 5.0,
    reviewCount: 89,
    includes: ["Balloon Flight", "Champagne Breakfast", "Certificate", "Transport"],
    excludes: ["Gratuities"],
    featured: true,
    maxParticipants: 16,
    minAge: 8,
  },
  {
    id: "night-drive",
    name: "Nocturnal Game Drive",
    slug: "nocturnal-game-drive",
    category: "Safari",
    duration: "3 hours",
    intensity: "Easy",
    coordinates: { lat: -25.4500, lng: 30.9833 },
    description: "Discover the mysterious creatures that come alive after dark.",
    longDescription:
      "As darkness falls, a different cast of characters emerges. Using powerful spotlights, our guides will help you discover owls, aardvarks, bush babies, and potentially big cats on the hunt.",
    image: "/night-safari.jpg",
    gallery: [
      "/spotlight-wildlife.jpg",
      "/leopard-in-tree-kruger-park.jpg",
      "/lion-pride-resting-african-savanna.jpg",
      "/stargazing-event.jpg",
    ],
    price: 750,
    rating: 4.8,
    reviewCount: 312,
    includes: ["Expert Guide", "Spotlight", "Hot Beverages", "Snacks"],
    excludes: ["Dinner", "Warm clothing"],
    featured: false,
    maxParticipants: 8,
    minAge: 8,
  },
  {
    id: "trout-fishing",
    name: "Fly Fishing Experience",
    slug: "fly-fishing-experience",
    category: "Water",
    duration: "Half day",
    intensity: "Easy",
    description: "Learn the art of fly fishing in the pristine trout waters of the Highveld.",
    longDescription: "Join expert anglers for a memorable fly fishing experience in Dullstroom, known as the trout fishing capital of South Africa. All equipment provided, suitable for beginners and experienced fishers alike.",
    image: "/fishing-boat-on-african-dam-sunset.jpg",
    gallery: [
      "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
      "/highveld-region.jpg",
      "/waterfront-cottage.jpg",
    ],
    price: 650,
    rating: 4.7,
    reviewCount: 234,
    includes: ["Equipment", "Guide", "Lunch", "Fishing License"],
    excludes: ["Accommodation", "Transport"],
    featured: false,
    maxParticipants: 4,
    minAge: 12,
    coordinates: { lat: -25.2833, lng: 30.1167 },
  },
  {
    id: "quad-biking",
    name: "Quad Biking Adventure",
    slug: "quad-biking-adventure",
    category: "Adventure",
    duration: "3 hours",
    intensity: "Moderate",
    description: "Explore scenic trails on powerful quad bikes through bush and farmland.",
    longDescription: "An adrenaline-pumping adventure through diverse terrain including bush tracks, river crossings, and scenic viewpoints. Professional guides ensure safety while maximizing the fun.",
    image: "/trail-run.jpg",
    gallery: [
      "/safari-jeep.jpg",
      "/barberton-valley.jpg",
      "/panorama-route.jpg",
    ],
    price: 750,
    rating: 4.6,
    reviewCount: 312,
    includes: ["Quad Bike", "Helmet", "Guide", "Refreshments"],
    excludes: ["Insurance excess", "Transport"],
    featured: false,
    maxParticipants: 10,
    minAge: 16,
    coordinates: { lat: -25.0500, lng: 30.9000 },
  },
  {
    id: "zip-lining",
    name: "Canyon Zip Line Tour",
    slug: "canyon-zip-line-tour",
    category: "Adventure",
    duration: "2 hours",
    intensity: "Moderate",
    description: "Soar over the Graskop Gorge on one of the world's highest cable gorge slides.",
    longDescription: "Experience the thrill of zip-lining across the dramatic Graskop Gorge. Multiple cables offer increasingly exciting rides with breathtaking views of the indigenous forest below.",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    gallery: [
      "/gods-window-panorama-view-mpumalanga.jpg",
      "/blyde-river-canyon-three-rondavels-viewpoint.jpg",
      "/panorama-route.jpg",
    ],
    price: 450,
    rating: 4.8,
    reviewCount: 567,
    includes: ["All Equipment", "Safety Briefing", "Guide", "Certificate"],
    excludes: ["Photos", "Transport"],
    featured: true,
    maxParticipants: 12,
    minAge: 10,
    coordinates: { lat: -24.9333, lng: 30.8333 },
  },
  {
    id: "horse-safari",
    name: "Horseback Safari",
    slug: "horseback-safari",
    category: "Safari",
    duration: "3 hours",
    intensity: "Moderate",
    description: "Experience the bush on horseback, getting closer to wildlife than ever before.",
    longDescription: "A unique way to experience the African bush. Ride through the reserve on well-trained horses, approaching wildlife in a non-threatening way that allows for remarkable close encounters.",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    gallery: [
      "/zebra-herd-african-plains.jpg",
      "/giraffe-silhouette-sunset-africa.jpg",
      "/sunrise-safari.jpg",
    ],
    price: 950,
    rating: 4.7,
    reviewCount: 189,
    includes: ["Horse", "Guide", "Helmet", "Refreshments"],
    excludes: ["Riding experience required", "Transport"],
    featured: false,
    maxParticipants: 8,
    minAge: 12,
    coordinates: { lat: -25.1000, lng: 31.0500 },
  },
  {
    id: "bush-braai",
    name: "Sunset Bush Braai",
    slug: "sunset-bush-braai",
    category: "Culture",
    duration: "4 hours",
    intensity: "Easy",
    description: "Traditional South African braai experience in the wilderness at sunset.",
    longDescription: "Join us for an authentic South African braai (barbecue) experience in a scenic bush setting. Enjoy traditional dishes, local wines, and live music as the sun sets over the African landscape.",
    image: "/bush-camp-fire.jpg",
    gallery: [
      "/giraffe-silhouette-sunset-africa.jpg",
      "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
      "/summer-safari-promo.jpg",
    ],
    price: 550,
    rating: 4.9,
    reviewCount: 423,
    includes: ["Full Braai Dinner", "Drinks", "Entertainment", "Transport from hotel"],
    excludes: ["Gratuities"],
    featured: true,
    maxParticipants: 30,
    minAge: 0,
    coordinates: { lat: -25.4500, lng: 30.9700 },
  },
  {
    id: "hot-springs",
    name: "Badplaas Hot Springs Experience",
    slug: "badplaas-hot-springs",
    category: "Wellness",
    duration: "3 hours",
    intensity: "Easy",
    description: "Relax in natural mineral hot springs surrounded by scenic mountains.",
    longDescription: "Unwind in the healing mineral waters of Badplaas hot springs. Multiple pools at varying temperatures offer the perfect relaxation experience in a beautiful natural setting.",
    image: "/canyon-lodge-pool.jpg",
    gallery: [
      "/barberton-valley.jpg",
      "/safari-chalet-deck.jpg",
    ],
    price: 180,
    rating: 4.7,
    reviewCount: 567,
    includes: ["Pool Access", "Towel", "Changing Facilities"],
    excludes: ["Spa Treatments", "Food"],
    featured: true,
    maxParticipants: 50,
    minAge: 0,
    coordinates: { lat: -25.9667, lng: 30.5833 },
  },
  {
    id: "lake-birding",
    name: "Chrissiesmeer Birding Safari",
    slug: "chrissiesmeer-birding",
    category: "Nature",
    duration: "Half day",
    intensity: "Easy",
    description: "Expert-guided birding tour through South Africa's lake district.",
    longDescription: "Join experienced birders to explore the wetlands around Chrissiesmeer, home to flamingos, pelicans, blue cranes, and over 200 bird species.",
    image: "/fishing-boat-on-african-dam-sunset.jpg",
    gallery: [
      "/loskop-dam-south-africa-scenic-lake-view-mountains.jpg",
      "/highveld-region.jpg",
    ],
    price: 450,
    rating: 4.6,
    reviewCount: 145,
    includes: ["Guide", "Binoculars", "Bird Checklist", "Refreshments"],
    excludes: ["Transport", "Lunch"],
    featured: false,
    maxParticipants: 8,
    minAge: 8,
    coordinates: { lat: -26.2833, lng: 30.2167 },
  },
  {
    id: "escarpment-drive",
    name: "Escarpment Scenic Drive",
    slug: "escarpment-scenic-drive",
    category: "Adventure",
    duration: "Full day",
    intensity: "Easy",
    description: "Self-drive or guided tour along the dramatic Mpumalanga escarpment.",
    longDescription: "Experience the breathtaking Mpumalanga escarpment with stops at viewpoints, waterfalls, and historic sites. Options for self-drive with detailed maps or guided tours available.",
    image: "/panorama-route.jpg",
    gallery: [
      "/gods-window-panorama-view-mpumalanga.jpg",
      "/blyde-river-canyon-three-rondavels-viewpoint.jpg",
      "/bourkes-luck-potholes-rock-formations.jpg",
    ],
    price: 350,
    rating: 4.8,
    reviewCount: 678,
    includes: ["Route Map", "Viewpoint Entry Fees", "Picnic Lunch"],
    excludes: ["Vehicle Rental", "Fuel"],
    featured: true,
    maxParticipants: 20,
    minAge: 0,
    coordinates: { lat: -24.8769, lng: 30.8892 },
  },
  {
    id: "coal-mine-tour",
    name: "Coal Mining Heritage Tour",
    slug: "coal-mining-tour",
    category: "Culture",
    duration: "3 hours",
    intensity: "Easy",
    description: "Discover the coal mining history that shaped the Highveld region.",
    longDescription: "An educational tour exploring the coal mining heritage of eMalahleni and surrounds. Visit historic sites, learn about mining processes, and understand the region's industrial importance.",
    image: "/ancient-rock-formations-barberton.jpg",
    gallery: [
      "/highveld-region.jpg",
    ],
    price: 280,
    rating: 4.3,
    reviewCount: 89,
    includes: ["Guide", "Safety Equipment", "Museum Entry"],
    excludes: ["Transport", "Refreshments"],
    featured: false,
    maxParticipants: 15,
    minAge: 12,
    coordinates: { lat: -25.8667, lng: 29.2333 },
  },
  {
    id: "gold-panning",
    name: "Gold Panning at Pilgrim's Rest",
    slug: "gold-panning-pilgrims-rest",
    category: "Adventure",
    duration: "2 hours",
    intensity: "Easy",
    description: "Try your luck panning for gold in historic Pilgrim's Rest.",
    longDescription: "Step back in time and experience the gold rush era. Learn traditional panning techniques and keep any gold you find in the streams of this historic mining town.",
    image: "/ancient-rock-formations-barberton.jpg",
    gallery: [
      "/panorama-route.jpg",
      "/barberton-valley.jpg",
    ],
    price: 150,
    rating: 4.5,
    reviewCount: 234,
    includes: ["Equipment", "Instruction", "Gold Vial"],
    excludes: ["Transport"],
    featured: false,
    maxParticipants: 12,
    minAge: 6,
    coordinates: { lat: -24.9000, lng: 30.7500 },
  },
  {
    id: "komati-gorge",
    name: "Komati Gorge Rafting",
    slug: "komati-gorge-rafting",
    category: "Adventure",
    duration: "Full day",
    intensity: "Difficult",
    description: "White water rafting through the dramatic Komati River gorge.",
    longDescription: "Experience the thrill of navigating grade 3-4 rapids through stunning gorge scenery. Professional guides ensure safety while maximizing the adventure.",
    image: "/dam-boat-cruise.jpg",
    gallery: [
      "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
      "/barberton-valley.jpg",
    ],
    price: 890,
    rating: 4.8,
    reviewCount: 178,
    includes: ["All Equipment", "Guides", "Lunch", "Transport from Badplaas"],
    excludes: ["Wetsuit Rental"],
    featured: true,
    maxParticipants: 16,
    minAge: 14,
    coordinates: { lat: -25.9500, lng: 30.6000 },
  },
]

export const events = [
  {
    id: "wildlife-photo",
    name: "Wildlife Photography Workshop",
    date: "2026-02-15",
    endDate: "2026-02-17",
    location: "Kruger Gate Reserve",
    description: "Three-day intensive workshop with professional wildlife photographers.",
    image: "/photo-workshop.jpg",
    price: 8500,
    category: "Workshop",
  },
  {
    id: "bush-run",
    name: "Lowveld Bush Run 2026",
    date: "2026-03-22",
    endDate: "2026-03-22",
    location: "Songimvelo Game Reserve",
    description: "Annual trail running event through the scenic game reserve.",
    image: "/trail-run.jpg",
    price: 350,
    category: "Sport",
  },
  {
    id: "star-gazing",
    name: "Dark Sky Festival",
    date: "2026-04-12",
    endDate: "2026-04-13",
    location: "Blyde River Canyon",
    description: "Experience the pristine night skies with expert astronomers.",
    image: "/stargazing-event.jpg",
    price: 650,
    category: "Festival",
  },
  {
    id: "marula-festival",
    name: "Marula Festival 2026",
    date: "2026-02-28",
    endDate: "2026-03-01",
    location: "Hazyview",
    description: "Celebrate the harvest of the marula fruit with traditional music, dance, and local cuisine.",
    image: "/cultural-village.jpg",
    price: 150,
    category: "Festival",
  },
  {
    id: "birding-week",
    name: "Mpumalanga Birding Big Day",
    date: "2026-05-09",
    endDate: "2026-05-09",
    location: "Chrissiesmeer Lake District",
    description: "Join birders across the province in counting as many species as possible in 24 hours.",
    image: "/fishing-boat-on-african-dam-sunset.jpg",
    price: 200,
    category: "Nature",
  },
  {
    id: "panorama-marathon",
    name: "Panorama Route Ultra Marathon",
    date: "2026-06-21",
    endDate: "2026-06-21",
    location: "Graskop to Sabie",
    description: "Challenge yourself on this scenic 50km ultra marathon along the famous Panorama Route.",
    image: "/panorama-route.jpg",
    price: 550,
    category: "Sport",
  },
  {
    id: "heritage-day",
    name: "Heritage Day Celebration",
    date: "2026-09-24",
    endDate: "2026-09-24",
    location: "Nelspruit",
    description: "A celebration of South African heritage with traditional food, music, and cultural displays.",
    image: "/traditional-dance.jpg",
    price: 0,
    category: "Cultural",
  },
  {
    id: "lowveld-show",
    name: "Lowveld Agricultural Show",
    date: "2026-08-14",
    endDate: "2026-08-16",
    location: "Nelspruit Showgrounds",
    description: "The biggest agricultural and lifestyle show in the Lowveld region.",
    image: "/lowveld-region.jpg",
    price: 80,
    category: "Show",
  },
  {
    id: "innibos",
    name: "Innibos Arts Festival",
    date: "2026-07-03",
    endDate: "2026-07-06",
    location: "Nelspruit",
    description: "Mpumalanga's premier arts and culture festival featuring music, theatre, and visual arts.",
    image: "/events-festival-hero.jpg",
    price: 250,
    category: "Festival",
  },
  {
    id: "safari-sunset",
    name: "Sunset Safari Soiree",
    date: "2026-04-25",
    endDate: "2026-04-25",
    location: "Sabi Sands Game Reserve",
    description: "An exclusive evening game drive followed by a gourmet bush dinner under the stars.",
    image: "/giraffe-silhouette-sunset-africa.jpg",
    price: 2500,
    category: "Experience",
  },
]

export const categories = [
  { id: "reserves", name: "Nature Reserves", icon: "Trees", count: 12 },
  { id: "accommodation", name: "Accommodation", icon: "Home", count: 45 },
  { id: "experiences", name: "Experiences", icon: "Compass", count: 38 },
  { id: "events", name: "Events", icon: "Calendar", count: 15 },
  { id: "business", name: "Business Tourism", icon: "Briefcase", count: 8 },
  { id: "trade", name: "Travel Trade", icon: "Users", count: 6 },
]

export const regions = [
  { id: "panorama", name: "Panorama Route", reserves: 4 },
  { id: "lowveld", name: "Lowveld", reserves: 5 },
  { id: "highveld", name: "Highveld", reserves: 3 },
  { id: "barberton", name: "Barberton Valley", reserves: 2 },
]

export const attractions = [
  {
    id: "gods-window",
    name: "God's Window",
    type: "viewpoint",
    location: "Graskop",
    region: "Panorama Route",
    coordinates: { lat: -24.8769, lng: 30.8892 },
    description: "Spectacular viewpoint with panoramic views over the Lowveld",
    image: "/gods-window-panorama-view-mpumalanga.jpg",
    priceFrom: 30,
    duration: "1-2 hours",
    accessible: true,
  },
  {
    id: "three-rondavels",
    name: "Three Rondavels",
    type: "viewpoint",
    location: "Blyde River Canyon",
    region: "Panorama Route",
    coordinates: { lat: -24.5667, lng: 30.8000 },
    description: "Iconic rock formations resembling traditional African huts",
    image: "/blyde-river-canyon-three-rondavels-viewpoint.jpg",
    priceFrom: 30,
    duration: "1 hour",
    accessible: true,
  },
  {
    id: "bourkes-luck",
    name: "Bourke's Luck Potholes",
    type: "natural",
    location: "Blyde River Canyon",
    region: "Panorama Route",
    coordinates: { lat: -24.6750, lng: 30.8083 },
    description: "Cylindrical rock formations carved by swirling water",
    image: "/bourkes-luck-potholes-rock-formations.jpg",
    priceFrom: 50,
    duration: "2 hours",
    accessible: true,
  },
  {
    id: "pilgrim-rest",
    name: "Pilgrim's Rest",
    type: "heritage",
    location: "Pilgrim's Rest",
    region: "Panorama Route",
    coordinates: { lat: -24.9000, lng: 30.7500 },
    description: "Historic gold mining town preserved as a living museum",
    image: "/ancient-rock-formations-barberton.jpg",
    priceFrom: 0,
    duration: "3-4 hours",
    accessible: true,
  },
  {
    id: "sudwala-caves",
    name: "Sudwala Caves",
    type: "natural",
    location: "Nelspruit",
    region: "Lowveld",
    coordinates: { lat: -25.3667, lng: 30.6833 },
    description: "Ancient dolomite caves with spectacular formations",
    image: "/ancient-rock-formations-barberton.jpg",
    priceFrom: 180,
    duration: "2 hours",
    accessible: false,
  },
  {
    id: "lowveld-botanical",
    name: "Lowveld National Botanical Garden",
    type: "garden",
    location: "Nelspruit",
    region: "Lowveld",
    coordinates: { lat: -25.4500, lng: 30.9667 },
    description: "Beautiful botanical garden with African rainforest and waterfalls",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    priceFrom: 45,
    duration: "2-3 hours",
    accessible: true,
  },
  {
    id: "chimp-eden",
    name: "Chimp Eden",
    type: "sanctuary",
    location: "Nelspruit",
    region: "Lowveld",
    coordinates: { lat: -25.4333, lng: 30.7833 },
    description: "Chimpanzee sanctuary and rehabilitation center",
    image: "/safari-wildlife.jpg",
    priceFrom: 225,
    duration: "2 hours",
    accessible: true,
  },
  {
    id: "sabie-falls",
    name: "Sabie Waterfalls Route",
    type: "waterfall",
    location: "Sabie",
    region: "Panorama Route",
    coordinates: { lat: -25.1000, lng: 30.7833 },
    description: "Series of magnificent waterfalls including Lisbon and Berlin Falls",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    priceFrom: 20,
    duration: "Half day",
    accessible: false,
  },
  {
    id: "mac-mac-falls",
    name: "Mac Mac Falls",
    type: "waterfall",
    location: "Sabie",
    region: "Panorama Route",
    coordinates: { lat: -25.0167, lng: 30.8167 },
    description: "Twin 65-meter waterfalls named after Scottish miners who discovered gold nearby",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    priceFrom: 30,
    duration: "1 hour",
    accessible: true,
  },
  {
    id: "pinnacle-rock",
    name: "The Pinnacle",
    type: "viewpoint",
    location: "Graskop",
    region: "Panorama Route",
    coordinates: { lat: -24.8500, lng: 30.8667 },
    description: "Towering quartzite column rising from dense indigenous forest",
    image: "/panorama-route.jpg",
    priceFrom: 20,
    duration: "30 mins",
    accessible: true,
  },
  {
    id: "long-tom-pass",
    name: "Long Tom Pass",
    type: "viewpoint",
    location: "Lydenburg",
    region: "Highveld",
    coordinates: { lat: -25.1167, lng: 30.5833 },
    description: "Scenic mountain pass with Anglo-Boer War history and stunning views",
    image: "/highveld-region.jpg",
    priceFrom: 0,
    duration: "1-2 hours",
    accessible: true,
  },
  {
    id: "kaapsehoop",
    name: "Kaapsehoop Village",
    type: "heritage",
    location: "Kaapsehoop",
    region: "Lowveld",
    coordinates: { lat: -25.5833, lng: 30.7667 },
    description: "Historic gold rush village famous for its wild horses and misty atmosphere",
    image: "/barberton-valley.jpg",
    priceFrom: 0,
    duration: "2-3 hours",
    accessible: true,
  },
  {
    id: "nelspruit-promenade",
    name: "Nelspruit Promenade",
    type: "garden",
    location: "Nelspruit",
    region: "Lowveld",
    coordinates: { lat: -25.4833, lng: 30.9833 },
    description: "Urban waterfront park with walking trails, restaurants and entertainment",
    image: "/waterfront-cottage.jpg",
    priceFrom: 0,
    duration: "2-4 hours",
    accessible: true,
  },
  {
    id: "echo-caves",
    name: "Echo Caves",
    type: "natural",
    location: "Ohrigstad",
    region: "Panorama Route",
    coordinates: { lat: -24.5000, lng: 30.5333 },
    description: "Spectacular dolomite caves with stalactites and archaeological significance",
    image: "/ancient-rock-formations-barberton.jpg",
    priceFrom: 95,
    duration: "1.5 hours",
    accessible: false,
  },
  {
    id: "dullstroom",
    name: "Dullstroom Village",
    type: "heritage",
    location: "Dullstroom",
    region: "Highveld",
    coordinates: { lat: -25.4167, lng: 30.1000 },
    description: "Charming highland village known as the trout capital of South Africa",
    image: "/highveld-region.jpg",
    priceFrom: 0,
    duration: "Half day",
    accessible: true,
  },
  {
    id: "komatipoort",
    name: "Komatipoort Border Town",
    type: "heritage",
    location: "Komatipoort",
    region: "Lowveld",
    coordinates: { lat: -25.4333, lng: 31.9500 },
    description: "Historic border town and gateway to Mozambique with tropical atmosphere",
    image: "/african-game-reserve-savanna-sunset-zebras-grazing.jpg",
    priceFrom: 0,
    duration: "2-3 hours",
    accessible: true,
  },
  {
    id: "malelane-gate",
    name: "Malelane Kruger Gate",
    type: "viewpoint",
    location: "Malelane",
    region: "Lowveld",
    coordinates: { lat: -25.4667, lng: 31.5333 },
    description: "Southern entrance to Kruger with visitor center and wildlife information",
    image: "/african-elephant-kruger-national-park-safari-wildl.jpg",
    priceFrom: 0,
    duration: "1 hour",
    accessible: true,
  },
  {
    id: "white-river",
    name: "White River",
    type: "heritage",
    location: "White River",
    region: "Lowveld",
    coordinates: { lat: -25.3333, lng: 31.0167 },
    description: "Charming town known for its nurseries, art galleries, and subtropical gardens",
    image: "/lowveld-region.jpg",
    priceFrom: 0,
    duration: "Half day",
    accessible: true,
  },
  {
    id: "ermelo",
    name: "Ermelo Town",
    type: "heritage",
    location: "Ermelo",
    region: "Highveld",
    coordinates: { lat: -26.5333, lng: 29.9833 },
    description: "Historic Highveld town with wool museum and access to lake district",
    image: "/highveld-region.jpg",
    priceFrom: 0,
    duration: "2-3 hours",
    accessible: true,
  },
  {
    id: "bethal",
    name: "Bethal Agricultural Town",
    type: "heritage",
    location: "Bethal",
    region: "Highveld",
    coordinates: { lat: -26.4500, lng: 29.4667 },
    description: "Heart of maize farming country with authentic rural Highveld experience",
    image: "/highveld-region.jpg",
    priceFrom: 0,
    duration: "2 hours",
    accessible: true,
  },
  {
    id: "crocodile-river",
    name: "Crocodile River Valley",
    type: "natural",
    location: "Nelspruit",
    region: "Lowveld",
    coordinates: { lat: -25.5167, lng: 31.0000 },
    description: "Scenic river valley with game farms, citrus orchards, and wildlife",
    image: "/giraffe-silhouette-sunset-africa.jpg",
    priceFrom: 0,
    duration: "Half day",
    accessible: true,
  },
  {
    id: "schoemanskloof",
    name: "Schoemanskloof Valley",
    type: "viewpoint",
    location: "Between Nelspruit and Lydenburg",
    region: "Lowveld",
    coordinates: { lat: -25.2833, lng: 30.6333 },
    description: "Dramatic mountain pass with waterfalls and indigenous forest",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    priceFrom: 0,
    duration: "2-3 hours",
    accessible: true,
  },
  {
    id: "montrose-falls",
    name: "Montrose Falls",
    type: "waterfall",
    location: "Schoemanskloof",
    region: "Lowveld",
    coordinates: { lat: -25.3000, lng: 30.6500 },
    description: "Beautiful waterfall accessible via short hiking trail",
    image: "/blyde-river-canyon-south-africa-dramatic-green-can.jpg",
    priceFrom: 20,
    duration: "1-2 hours",
    accessible: false,
  },
  {
    id: "burgersfort",
    name: "Burgersfort",
    type: "heritage",
    location: "Burgersfort",
    region: "Highveld",
    coordinates: { lat: -24.6667, lng: 30.3500 },
    description: "Mining town gateway to the northern escarpment and Mapoch Caves",
    image: "/ancient-rock-formations-barberton.jpg",
    priceFrom: 0,
    duration: "1-2 hours",
    accessible: true,
  },
  {
    id: "middelburg",
    name: "Middelburg",
    type: "heritage",
    location: "Middelburg",
    region: "Highveld",
    coordinates: { lat: -25.7833, lng: 29.4667 },
    description: "Historic town with Anglo-Boer War heritage and access to Loskop Dam",
    image: "/highveld-region.jpg",
    priceFrom: 0,
    duration: "2-3 hours",
    accessible: true,
  },
  {
    id: "hazyview",
    name: "Hazyview Town",
    type: "heritage",
    location: "Hazyview",
    region: "Lowveld",
    coordinates: { lat: -25.0500, lng: 31.1333 },
    description: "Adventure hub near Kruger with markets, restaurants, and activities",
    image: "/safari-jeep.jpg",
    priceFrom: 0,
    duration: "Half day",
    accessible: true,
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Sarah Mitchell",
    location: "London, UK",
    text: "An absolutely magical experience. The Blyde River Canyon took my breath away, and the staff made everything seamless.",
    rating: 5,
    image: "/avatar-sarah.jpg",
  },
  {
    id: 2,
    name: "Hans Weber",
    location: "Munich, Germany",
    text: "Best safari experience of our lives. Saw all the Big Five in just two days. Highly recommend the sunrise game drive.",
    rating: 5,
    image: "/avatar-hans.jpg",
  },
  {
    id: 3,
    name: "Thandi Nkosi",
    location: "Johannesburg, SA",
    text: "As a South African, I'm proud of what MTPA has created. World-class facilities showcasing our beautiful province.",
    rating: 5,
    image: "/avatar-thandi.jpg",
  },
]
